- name: Install packages
  hosts: all
  tasks:
    - name: Install chrony and nslookup on RedHat nodes
      when: ansible_facts['os_family'] == 'RedHat'
      ansible.builtin.dnf:
        name: 
          - chrony
          - bind-utils
        state: present
    - name: Install chrony and nslookup on Debian nodes
      when: ansible_facts['os_family'] == 'Debian'
      ansible.builtin.apt:
        name:
          - chrony
          - dnsutils
        state: present

- name: Setup DNS
  hosts: all
  tasks:
    - name: Check DNS status on RedHat nodes
      when: ansible_facts['os_family'] == 'RedHat'
      ansible.builtin.shell: cat /etc/resolv.conf | grep {{ name_server }}
      register: check_dns_alma
      ignore_errors: yes
      changed_when: false

    - name: Setup DNS on RedHat nodes
      when: ansible_facts['os_family'] == 'RedHat' and check_dns_alma is failed
      ansible.builtin.shell: |
        set -e
        con_name=$(nmcli -t --fields=NAME con show --active | awk -F: '{ print $1 }' | head -n 1) 
        nmcli con modify "$con_name" ipv4.dns {{ name_server }} ipv4.ignore-auto-dns yes
        nmcli con down "$con_name" && nmcli con up "$con_name" 
      register: nmcli_configure
      ignore_errors: yes

    - name: Resolv.conf fallback for Alama nodes
      when: ansible_facts['os_family'] == 'RedHat' and nmcli_configure is failed
      ansible.builtin.lineinfile:
        path: /etc/resolv.conf
        search_string: 'nameserver'
        line: 'nameserver {{ name_server }}'

    - name: Disable Systemd Resolved on Debian nodes
      when: ansible_facts['os_family'] == 'Debian'
      ansible.builtin.service:
        name: systemd-resolved
        state: stopped
      register: systemd_resolved

    - name: Delete leftover resolv.conf
      when: ansible_facts['os_family'] == 'Debian' and systemd_resolved is changed
      ansible.builtin.file:
        path: /etc/resolv.conf
        state: absent

    - name: Setup DNS on Debian nodes
      when: ansible_facts['os_family'] == 'Debian'
      ansible.builtin.blockinfile:
        path: /etc/resolv.conf
        block: |
          nameserver {{ name_server }} 
          search {{ search_domain  }}
        create: true

- name: Setup NTP
  hosts: all
  handlers:
    - name: Restart Chrony
      ansible.builtin.service:
        name: chronyd
        state: restarted
  tasks:
    - name: Start Chronyd on all nodes
      ansible.builtin.service:
        name: chronyd
        state: started

    - name: Configure NTP Server for RedHat nodes
      when: ansible_facts['os_family'] == 'RedHat'
      ansible.builtin.lineinfile:
        path: /etc/chrony.conf
        search_string: 'pool'
        line: 'pool {{ ntp_server }} iburst'
      notify: Restart Chrony
    
    - name: Configure NTP Server for Debian nodes
      when: ansible_facts['os_family'] == 'Debian'
      ansible.builtin.lineinfile:
        path: /etc/chrony/chrony.conf
        search_string: 'pool'
        line: 'pool {{ ntp_server }} iburst'
      notify: Restart Chrony

    - name: Set timezone on all nodes
      ansible.builtin.file:
        src: /usr/share/zoneinfo/Asia/Yangon
        dest: /etc/localtime
        owner: root
        group: root
        state: link
