- name: Install Web Server on ansible nodes
  hosts: ansible_nodes
  tasks:
    - name: Install Web Server on alma nodes
      ansible.builtin.dnf:
        name: httpd
        state: present
      when: ansible_facts['os_family'] == 'RedHat'
    - name: Install Web Server on ubuntu nodes
      ansible.builtin.apt:
        name: apache2
        state: present
      when: ansible_facts['os_family'] == 'Debian'
