- name: Test variables
  hosts: ansible_nodes
  tasks:
    - name: Install packages
      ansible.builtin.package:
        name: '{{ app_list }}'
        state: present
    - name: Create group
      ansible.builtin.group:
        name: '{{ user_details.group }}'
        state: present
    - name: Create user account
      ansible.builtin.user:
        name: '{{ user_details.username }}'
        groups: '{{ user_details.group }}'
        comment: '{{ user_details.email }}'
